# Dependabot will run on day 13 of each month at 03:11 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "11 3 13 * *"
    open-pull-requests-limit: 20
    assignees:
      - "crycode-de"
    versioning-strategy: "increase"
